<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rizwan" ignored="0" name="Test" tests="4" failures="1" timestamp="22 Oct 2017 05:43:40 GMT" time="0.062" errors="0">
  <testcase name="LoginTest" time="0.017" classname="keywordTest.HardAssertTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at keywordTest.HardAssertTest.LoginTest(HardAssertTest.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase name="logintest" time="0.002" classname="keywordTest.ExpectedExceptionTest"/>
  <testcase name="logintest" time="0.001" classname="keywordTest.DescriptionTest"/>
  <testcase name="logintest" time="0.002" classname="keywordTest.DependsOnTest"/>
</testsuite> <!-- Test -->
